In [8]:
import numpy as np
np.random.seed(3)


# Converting list to Array

In [12]:
lst=[1,2,3,4]
print(type(lst))

arr=np.array(lst) #Converting list to array
print(type(arr))

arr=np.array(lst, ndmin=1)
print(arr)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4]


In [5]:
arr=np.array(lst)
print(type(arr))

<class 'numpy.ndarray'>


In [11]:
arr=np.array(lst, ndmin=5)

print(arr)

[[[[[1 2 3 4]]]]]


In [9]:
print(arr)

[1 2 3 4]


In [7]:
np.random.seed(3)

NameError: name 'np' is not defined